apiVersion: v1
kind: Service
metadata:
  name: myapp-service-green
spec:
  selector:
    app: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  externalIPs:
    - 103.146.224.225
